// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_pro_test/test/features/admin/presentation/bloc/admin_dashboard_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i4;
import 'package:flutter_pro_test/core/errors/failures.dart' as _i7;
import 'package:flutter_pro_test/features/admin/domain/entities/booking_analytics.dart'
    as _i10;
import 'package:flutter_pro_test/features/admin/domain/entities/system_metrics.dart'
    as _i8;
import 'package:flutter_pro_test/features/admin/domain/repositories/admin_repository.dart'
    as _i3;
import 'package:flutter_pro_test/features/admin/domain/repositories/analytics_repository.dart'
    as _i2;
import 'package:flutter_pro_test/features/admin/domain/usecases/get_booking_analytics.dart'
    as _i9;
import 'package:flutter_pro_test/features/admin/domain/usecases/get_system_metrics.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAnalyticsRepository_0 extends _i1.SmartFake
    implements _i2.AnalyticsRepository {
  _FakeAnalyticsRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdminRepository_1 extends _i1.SmartFake
    implements _i3.AdminRepository {
  _FakeAdminRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetSystemMetrics].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSystemMetrics extends _i1.Mock implements _i5.GetSystemMetrics {
  MockGetSystemMetrics() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AnalyticsRepository get analyticsRepository =>
      (super.noSuchMethod(
            Invocation.getter(#analyticsRepository),
            returnValue: _FakeAnalyticsRepository_0(
              this,
              Invocation.getter(#analyticsRepository),
            ),
          )
          as _i2.AnalyticsRepository);

  @override
  _i3.AdminRepository get adminRepository =>
      (super.noSuchMethod(
            Invocation.getter(#adminRepository),
            returnValue: _FakeAdminRepository_1(
              this,
              Invocation.getter(#adminRepository),
            ),
          )
          as _i3.AdminRepository);

  @override
  _i6.Future<_i4.Either<_i7.Failure, _i8.SystemMetrics>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i6.Future<_i4.Either<_i7.Failure, _i8.SystemMetrics>>.value(
                  _FakeEither_2<_i7.Failure, _i8.SystemMetrics>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i6.Future<_i4.Either<_i7.Failure, _i8.SystemMetrics>>);
}

/// A class which mocks [GetBookingAnalytics].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBookingAnalytics extends _i1.Mock
    implements _i9.GetBookingAnalytics {
  MockGetBookingAnalytics() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AnalyticsRepository get analyticsRepository =>
      (super.noSuchMethod(
            Invocation.getter(#analyticsRepository),
            returnValue: _FakeAnalyticsRepository_0(
              this,
              Invocation.getter(#analyticsRepository),
            ),
          )
          as _i2.AnalyticsRepository);

  @override
  _i3.AdminRepository get adminRepository =>
      (super.noSuchMethod(
            Invocation.getter(#adminRepository),
            returnValue: _FakeAdminRepository_1(
              this,
              Invocation.getter(#adminRepository),
            ),
          )
          as _i3.AdminRepository);

  @override
  _i6.Future<_i4.Either<_i7.Failure, _i10.BookingAnalytics>> call(
    _i9.GetBookingAnalyticsParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i6.Future<
                  _i4.Either<_i7.Failure, _i10.BookingAnalytics>
                >.value(
                  _FakeEither_2<_i7.Failure, _i10.BookingAnalytics>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i6.Future<_i4.Either<_i7.Failure, _i10.BookingAnalytics>>);
}

/// A class which mocks [AnalyticsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsRepository extends _i1.Mock
    implements _i2.AnalyticsRepository {
  MockAnalyticsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Either<_i7.Failure, _i8.SystemMetrics>> getSystemMetrics() =>
      (super.noSuchMethod(
            Invocation.method(#getSystemMetrics, []),
            returnValue:
                _i6.Future<_i4.Either<_i7.Failure, _i8.SystemMetrics>>.value(
                  _FakeEither_2<_i7.Failure, _i8.SystemMetrics>(
                    this,
                    Invocation.method(#getSystemMetrics, []),
                  ),
                ),
          )
          as _i6.Future<_i4.Either<_i7.Failure, _i8.SystemMetrics>>);

  @override
  _i6.Stream<_i4.Either<_i7.Failure, _i8.SystemMetrics>> watchSystemMetrics() =>
      (super.noSuchMethod(
            Invocation.method(#watchSystemMetrics, []),
            returnValue:
                _i6.Stream<_i4.Either<_i7.Failure, _i8.SystemMetrics>>.empty(),
          )
          as _i6.Stream<_i4.Either<_i7.Failure, _i8.SystemMetrics>>);

  @override
  _i6.Future<_i4.Either<_i7.Failure, _i10.BookingAnalytics>>
  getBookingAnalytics({
    required DateTime? startDate,
    required DateTime? endDate,
    String? serviceId,
    String? partnerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBookingAnalytics, [], {
              #startDate: startDate,
              #endDate: endDate,
              #serviceId: serviceId,
              #partnerId: partnerId,
            }),
            returnValue:
                _i6.Future<
                  _i4.Either<_i7.Failure, _i10.BookingAnalytics>
                >.value(
                  _FakeEither_2<_i7.Failure, _i10.BookingAnalytics>(
                    this,
                    Invocation.method(#getBookingAnalytics, [], {
                      #startDate: startDate,
                      #endDate: endDate,
                      #serviceId: serviceId,
                      #partnerId: partnerId,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i4.Either<_i7.Failure, _i10.BookingAnalytics>>);

  @override
  _i6.Future<_i4.Either<_i7.Failure, _i2.PartnerAnalytics>>
  getPartnerAnalytics({
    required DateTime? startDate,
    required DateTime? endDate,
    String? serviceId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPartnerAnalytics, [], {
              #startDate: startDate,
              #endDate: endDate,
              #serviceId: serviceId,
            }),
            returnValue:
                _i6.Future<_i4.Either<_i7.Failure, _i2.PartnerAnalytics>>.value(
                  _FakeEither_2<_i7.Failure, _i2.PartnerAnalytics>(
                    this,
                    Invocation.method(#getPartnerAnalytics, [], {
                      #startDate: startDate,
                      #endDate: endDate,
                      #serviceId: serviceId,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i4.Either<_i7.Failure, _i2.PartnerAnalytics>>);

  @override
  _i6.Future<_i4.Either<_i7.Failure, _i2.UserAnalytics>> getUserAnalytics({
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserAnalytics, [], {
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue:
                _i6.Future<_i4.Either<_i7.Failure, _i2.UserAnalytics>>.value(
                  _FakeEither_2<_i7.Failure, _i2.UserAnalytics>(
                    this,
                    Invocation.method(#getUserAnalytics, [], {
                      #startDate: startDate,
                      #endDate: endDate,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i4.Either<_i7.Failure, _i2.UserAnalytics>>);

  @override
  _i6.Future<_i4.Either<_i7.Failure, _i2.RevenueAnalytics>>
  getRevenueAnalytics({
    required DateTime? startDate,
    required DateTime? endDate,
    String? serviceId,
    String? partnerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRevenueAnalytics, [], {
              #startDate: startDate,
              #endDate: endDate,
              #serviceId: serviceId,
              #partnerId: partnerId,
            }),
            returnValue:
                _i6.Future<_i4.Either<_i7.Failure, _i2.RevenueAnalytics>>.value(
                  _FakeEither_2<_i7.Failure, _i2.RevenueAnalytics>(
                    this,
                    Invocation.method(#getRevenueAnalytics, [], {
                      #startDate: startDate,
                      #endDate: endDate,
                      #serviceId: serviceId,
                      #partnerId: partnerId,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i4.Either<_i7.Failure, _i2.RevenueAnalytics>>);

  @override
  _i6.Future<_i4.Either<_i7.Failure, _i2.SystemHealth>> getSystemHealth() =>
      (super.noSuchMethod(
            Invocation.method(#getSystemHealth, []),
            returnValue:
                _i6.Future<_i4.Either<_i7.Failure, _i2.SystemHealth>>.value(
                  _FakeEither_2<_i7.Failure, _i2.SystemHealth>(
                    this,
                    Invocation.method(#getSystemHealth, []),
                  ),
                ),
          )
          as _i6.Future<_i4.Either<_i7.Failure, _i2.SystemHealth>>);

  @override
  _i6.Stream<_i4.Either<_i7.Failure, _i2.SystemHealth>> watchSystemHealth() =>
      (super.noSuchMethod(
            Invocation.method(#watchSystemHealth, []),
            returnValue:
                _i6.Stream<_i4.Either<_i7.Failure, _i2.SystemHealth>>.empty(),
          )
          as _i6.Stream<_i4.Either<_i7.Failure, _i2.SystemHealth>>);

  @override
  _i6.Future<_i4.Either<_i7.Failure, String>> exportAnalyticsData({
    required _i2.AnalyticsExportType? type,
    required DateTime? startDate,
    required DateTime? endDate,
    required _i2.AnalyticsExportFormat? format,
    Map<String, dynamic>? filters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#exportAnalyticsData, [], {
              #type: type,
              #startDate: startDate,
              #endDate: endDate,
              #format: format,
              #filters: filters,
            }),
            returnValue: _i6.Future<_i4.Either<_i7.Failure, String>>.value(
              _FakeEither_2<_i7.Failure, String>(
                this,
                Invocation.method(#exportAnalyticsData, [], {
                  #type: type,
                  #startDate: startDate,
                  #endDate: endDate,
                  #format: format,
                  #filters: filters,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.Either<_i7.Failure, String>>);

  @override
  _i6.Future<_i4.Either<_i7.Failure, _i2.AnalyticsSummary>>
  getAnalyticsSummary({
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAnalyticsSummary, [], {
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue:
                _i6.Future<_i4.Either<_i7.Failure, _i2.AnalyticsSummary>>.value(
                  _FakeEither_2<_i7.Failure, _i2.AnalyticsSummary>(
                    this,
                    Invocation.method(#getAnalyticsSummary, [], {
                      #startDate: startDate,
                      #endDate: endDate,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i4.Either<_i7.Failure, _i2.AnalyticsSummary>>);

  @override
  _i6.Future<_i4.Either<_i7.Failure, _i2.ComparativeAnalytics>>
  getComparativeAnalytics({
    required DateTime? currentStart,
    required DateTime? currentEnd,
    required DateTime? previousStart,
    required DateTime? previousEnd,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getComparativeAnalytics, [], {
              #currentStart: currentStart,
              #currentEnd: currentEnd,
              #previousStart: previousStart,
              #previousEnd: previousEnd,
            }),
            returnValue:
                _i6.Future<
                  _i4.Either<_i7.Failure, _i2.ComparativeAnalytics>
                >.value(
                  _FakeEither_2<_i7.Failure, _i2.ComparativeAnalytics>(
                    this,
                    Invocation.method(#getComparativeAnalytics, [], {
                      #currentStart: currentStart,
                      #currentEnd: currentEnd,
                      #previousStart: previousStart,
                      #previousEnd: previousEnd,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i4.Either<_i7.Failure, _i2.ComparativeAnalytics>>);

  @override
  _i6.Future<_i4.Either<_i7.Failure, _i2.TopPerformingMetrics>>
  getTopPerformingMetrics({
    required DateTime? startDate,
    required DateTime? endDate,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTopPerformingMetrics, [], {
              #startDate: startDate,
              #endDate: endDate,
              #limit: limit,
            }),
            returnValue:
                _i6.Future<
                  _i4.Either<_i7.Failure, _i2.TopPerformingMetrics>
                >.value(
                  _FakeEither_2<_i7.Failure, _i2.TopPerformingMetrics>(
                    this,
                    Invocation.method(#getTopPerformingMetrics, [], {
                      #startDate: startDate,
                      #endDate: endDate,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i4.Either<_i7.Failure, _i2.TopPerformingMetrics>>);

  @override
  _i6.Future<_i4.Either<_i7.Failure, List<_i2.AnalyticsAlert>>>
  getAnalyticsAlerts({
    _i2.AnalyticsAlertSeverity? severity,
    bool? unreadOnly = false,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAnalyticsAlerts, [], {
              #severity: severity,
              #unreadOnly: unreadOnly,
              #limit: limit,
            }),
            returnValue:
                _i6.Future<
                  _i4.Either<_i7.Failure, List<_i2.AnalyticsAlert>>
                >.value(
                  _FakeEither_2<_i7.Failure, List<_i2.AnalyticsAlert>>(
                    this,
                    Invocation.method(#getAnalyticsAlerts, [], {
                      #severity: severity,
                      #unreadOnly: unreadOnly,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i4.Either<_i7.Failure, List<_i2.AnalyticsAlert>>>);

  @override
  _i6.Future<_i4.Either<_i7.Failure, void>> markAlertAsRead(String? alertId) =>
      (super.noSuchMethod(
            Invocation.method(#markAlertAsRead, [alertId]),
            returnValue: _i6.Future<_i4.Either<_i7.Failure, void>>.value(
              _FakeEither_2<_i7.Failure, void>(
                this,
                Invocation.method(#markAlertAsRead, [alertId]),
              ),
            ),
          )
          as _i6.Future<_i4.Either<_i7.Failure, void>>);

  @override
  _i6.Future<_i4.Either<_i7.Failure, Map<String, dynamic>>> executeCustomQuery({
    required String? query,
    Map<String, dynamic>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#executeCustomQuery, [], {
              #query: query,
              #parameters: parameters,
            }),
            returnValue:
                _i6.Future<_i4.Either<_i7.Failure, Map<String, dynamic>>>.value(
                  _FakeEither_2<_i7.Failure, Map<String, dynamic>>(
                    this,
                    Invocation.method(#executeCustomQuery, [], {
                      #query: query,
                      #parameters: parameters,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i4.Either<_i7.Failure, Map<String, dynamic>>>);
}
